import Foundation
import Testing
@testable import ExerlyCore

/// Programs generated for every combination of days, goal, experience, gym
/// and session length, written to docs/api/golden/program-generation-v1.json.
/// The API's port (apps/api/tests/training.generation.test.js) asserts the same
/// file, so an agent asking the API gets the program the app would build.
/// Regenerate with `EXERLY_WRITE_GOLDEN=1 swift test --filter GenerationGoldenTests`.
@Suite struct GenerationGoldenTests {
    static let url = GoldenTests.url.deletingLastPathComponent().appendingPathComponent("program-generation-v1.json")

    struct Gym: Encodable {
        var equipment: [Equipment]
        var excluded: [ExerciseID]
    }

    struct Request: Encodable {
        var daysPerWeek: Int, goal: String, experience: String, emphasis: [String], minutes: Int
    }

    struct Day: Encodable {
        var name: String
        /// Exercise, sets, minimum and maximum reps, RIR.
        var slots: [[JSONValue]]
    }

    struct Expected: Encodable {
        var name: String, cycles: Int, deload: String, days: [Day]
        var weeklySets: [String: Double], targets: [String: Double], shortfalls: [String]
    }

    struct Case: Encodable {
        var request: Request
        var gym: Gym?
        var expected: Expected
    }

    struct Golden: Encodable {
        var version = 1
        var note = "Generated by ExerlyCore GenerationGoldenTests; asserted by the Swift and JavaScript test suites."
        var cases: [Case]
    }

    static func cases() throws -> [Case] {
        let full = GymProfile(name: "Full")
        let gyms: [GymProfile?] = [nil, GymProfile(name: "Home", equipment: [.dumbbell, .flatBench, .inclineBench, .pullUpBar]),
                                   GymProfile(name: "Bodyweight", equipment: [.pullUpBar])]
        var excluding = full
        excluding.excluded = ["back-squat", "barbell-row", "pull-up", "dumbbell-lateral-raise"]
        var requests: [(ProgramGeneration.Request, GymProfile?)] = []
        for gym in gyms {
            for days in 2...6 {
                for goal in ProgramGeneration.Goal.allCases {
                    for level in ProgramGeneration.Experience.allCases {
                        for minutes in [60, 90] {
                            requests.append((.init(daysPerWeek: days, goal: goal, experience: level, minutes: minutes), gym))
                        }
                    }
                }
            }
        }
        for days in 2...6 {
            for goal in ProgramGeneration.Goal.allCases {
                requests.append((.init(daysPerWeek: days, goal: goal, experience: .intermediate, minutes: 75), excluding))
            }
        }
        requests += [
            (.init(daysPerWeek: 4, goal: .hypertrophy, experience: .intermediate, emphasis: [.chest, .sideDelts], minutes: 90), nil),
            (.init(daysPerWeek: 3, goal: .general, experience: .beginner, emphasis: [.glutes, .frontDelts], minutes: 45), nil),
            (.init(daysPerWeek: 6, goal: .strength, experience: .advanced, emphasis: [.quads], minutes: 120), nil),
            (.init(daysPerWeek: 2, goal: .hypertrophy, experience: .advanced, emphasis: [.biceps, .triceps], minutes: 30), nil),
        ]
        let library = ExerciseLibrary.bundled
        return try requests.map { request, gym in
            let result = try ProgramGeneration.generate(request, library: library, gym: gym)
            let program = result.program
            let days = program.days.map { day in
                Day(name: day.name, slots: day.slots.map { slot in
                    [.string(slot.exerciseID.rawValue), .number(Double(slot.target.sets)), .number(Double(slot.target.minReps)),
                     .number(Double(slot.target.maxReps)), .number(slot.target.rir)]
                })
            }
            let names = { (values: [Muscle: Double]) in Dictionary(uniqueKeysWithValues: values.map { ($0.key.rawValue, $0.value) }) }
            return Case(request: Request(daysPerWeek: request.daysPerWeek, goal: request.goal.rawValue,
                                         experience: request.experience.rawValue, emphasis: request.emphasis.map(\.rawValue),
                                         minutes: request.minutes),
                        gym: gym.map { Gym(equipment: $0.equipment, excluded: $0.excluded) },
                        expected: Expected(name: program.name, cycles: program.cycles, deload: program.deload.rawValue, days: days,
                                           weeklySets: names(result.weeklySets), targets: names(result.targets),
                                           shortfalls: result.shortfalls.map(\.rawValue)))
        }
    }

    @Test func theGoldenFileMatchesTheSwiftGenerator() throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
        let generated = try encoder.encode(Golden(cases: Self.cases()))
        if ProcessInfo.processInfo.environment["EXERLY_WRITE_GOLDEN"] != nil {
            try (generated + Data("\n".utf8)).write(to: Self.url)
        }
        let saved = try JSONValue(data: Data(contentsOf: Self.url))
        #expect(saved == (try JSONValue(data: generated)), "Regenerate with EXERLY_WRITE_GOLDEN=1 after an intended change")
    }
}
