import Foundation
import Testing
@testable import ExerlyCore

/// The training maths on a deterministic synthetic history, written to
/// docs/api/golden/training-v1.json. The API's JavaScript port asserts the same
/// file (apps/api/tests/training.golden.test.js), so the two can't drift.
/// Regenerate with `EXERLY_WRITE_GOLDEN=1 swift test --filter GoldenTests`.
@Suite struct GoldenTests {
    static let url = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        .appendingPathComponent("docs/api/golden/training-v1.json")

    @Test func theGoldenFileMatchesTheSwiftCalculations() throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys, .prettyPrinted, .withoutEscapingSlashes]
        let generated = try encoder.encode(GoldenHistory.make())
        if ProcessInfo.processInfo.environment["EXERLY_WRITE_GOLDEN"] != nil {
            try FileManager.default.createDirectory(at: Self.url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try (generated + Data("\n".utf8)).write(to: Self.url)
        }
        let saved = try JSONValue(data: Data(contentsOf: Self.url))
        #expect(saved == (try JSONValue(data: generated)), "Regenerate with EXERLY_WRITE_GOLDEN=1 after an intended change")
    }
}

/// Deterministic pseudo-random numbers (a 64-bit LCG), so the history is the same on every run.
private struct Seeded {
    var state: UInt64
    mutating func next() -> UInt64 {
        state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
        return state >> 33
    }
    mutating func int(_ range: ClosedRange<Int>) -> Int { range.lowerBound + Int(next() % UInt64(range.count)) }
    mutating func chance(_ percent: Int) -> Bool { int(0...99) < percent }
    mutating func pick<T>(_ items: [T]) -> T { items[int(0...items.count - 1)] }
}

private struct GoldenHistory: Encodable {
    var version = 1
    var note = "Synthetic data. Generated by ExerlyCore GoldenTests; asserted by the Swift and JavaScript test suites."
    var customExercises: [JSONValue]
    var sessions: [JSONValue]
    var expected: Expected

    struct TonnageJSON: Encodable {
        var resistance: Double, bodyweight: Double, total: Double, isComplete: Bool
        init(_ t: Tonnage) {
            resistance = t.resistance
            bodyweight = t.bodyweight
            total = t.total
            isComplete = t.isComplete
        }
    }

    struct VolumeJSON: Encodable {
        var sets: Double, tonnage: TonnageJSON
        init(_ v: MuscleVolume) {
            sets = v.sets
            tonnage = TonnageJSON(v.tonnage)
        }
    }

    struct SetJSON: Encodable {
        var session: String, set: String, exercise: String
        var oneRepMax: Double?, effectiveLoad: Double?, credit: Double, tonnage: TonnageJSON
    }

    struct SummaryJSON: Encodable {
        var session: String, localDate: String, exerciseCount: Int, totalSets: Int, completedSets: Int, workingSets: Int
        var duration: Double, tonnage: TonnageJSON, muscles: [String: VolumeJSON]
    }

    struct StatisticsJSON: Encodable {
        var estimatedOneRepMax: Double?, estimatedThreeRepMax: Double?, estimatedTenRepMax: Double?
        var totalVolume: Double, isVolumeComplete: Bool, bestSetVolume: Double, heaviestLoad: Double?
        var totalReps: Int, bestSetReps: Int, totalDuration: Double, bestSetDuration: Double
        var totalDistance: Double, bestSetDistance: Double, totalSets: Int
        init(_ s: ExerciseStatistics) {
            estimatedOneRepMax = s.estimatedOneRepMax?.kilograms
            estimatedThreeRepMax = s.estimatedThreeRepMax?.kilograms
            estimatedTenRepMax = s.estimatedTenRepMax?.kilograms
            totalVolume = s.totalVolume
            isVolumeComplete = s.isVolumeComplete
            bestSetVolume = s.bestSetVolume
            heaviestLoad = s.heaviestLoad?.kilograms
            totalReps = s.totalReps
            bestSetReps = s.bestSetReps
            totalDuration = s.totalDuration
            bestSetDuration = s.bestSetDuration
            totalDistance = s.totalDistance
            bestSetDistance = s.bestSetDistance
            totalSets = s.totalSets
        }
    }

    struct RangeStatisticsJSON: Encodable {
        var exercise: String, from: String, through: String, statistics: StatisticsJSON?
    }

    struct TrendPointJSON: Encodable { var date: String, session: String, oneRepMax: Double }

    struct RecordJSON: Encodable {
        var kind: String, exercise: String, session: String, set: String, value: Double, previous: Double, load: Double?
    }

    struct MetricJSON: Encodable {
        var reference: MetricReference, status: String, actual: Double?
    }

    struct SearchJSON: Encodable { var query: String, muscle: String?, results: [String] }

    struct Expected: Encodable {
        var sets: [SetJSON]
        var summaries: [SummaryJSON]
        var statistics: [String: StatisticsJSON]
        var statisticsInRange: [RangeStatisticsJSON]
        var trends: [String: [TrendPointJSON]]
        var records: [String: [RecordJSON]]
        var weeklyVolume: [String: [String: [String: VolumeJSON]]]
        var metrics: [MetricJSON]
        var search: [SearchJSON]
    }

    static func uuid(_ n: Int) -> UUID { UUID(uuidString: String(format: "00000000-0000-4000-8000-%012d", n))! }

    static func make() throws -> GoldenHistory {
        let custom = Exercise(id: "custom-golden-zercher-squat", name: "Zercher Squat", aliases: ["Zercher"], metric: .weightReps,
                              mechanics: .compound, region: .lower, muscles: [.quads: 1, .glutes: 1, .upperTraps: 0.5],
                              equipment: [.barbell], support: [.rack])
        let library = try ExerciseLibrary.bundled.adding(custom)
        let sessions = makeSessions()
        let finished = sessions.filter(\.isFinished)
        let history = TrainingHistory(sessions: finished, library: library)

        var sets: [SetJSON] = []
        for session in sessions {
            for performed in session.exercises {
                guard let exercise = library.exercise(performed.exerciseID) else { continue }
                for set in performed.sets {
                    sets.append(SetJSON(
                        session: session.id.uuidString, set: set.id.uuidString, exercise: exercise.id.rawValue,
                        oneRepMax: ExerciseStatistics.oneRepMax(set, exercise: exercise, bodyweight: session.bodyweight),
                        effectiveLoad: Volume.effectiveLoad(set.primary, exercise: exercise, bodyweight: session.bodyweight),
                        credit: Volume.setCredit(set, exercise: exercise),
                        tonnage: TonnageJSON(Volume.tonnage(set, exercise: exercise, bodyweight: session.bodyweight))))
                }
            }
        }

        let now = Date.milliseconds(1_800_000_000_000)
        let summaries = sessions.map { session in
            let summary = WorkoutSummary(session: session, library: library, at: now)
            return SummaryJSON(session: session.id.uuidString, localDate: session.localDate.description,
                               exerciseCount: summary.exerciseCount, totalSets: summary.totalSets,
                               completedSets: summary.completedSets, workingSets: summary.workingSets,
                               duration: summary.duration, tonnage: TonnageJSON(summary.tonnage),
                               muscles: volumeJSON(summary.muscles))
        }

        let exerciseIDs = Set(finished.flatMap { $0.exercises.map(\.exerciseID) }).sorted()
        var statistics: [String: StatisticsJSON] = [:]
        var trends: [String: [TrendPointJSON]] = [:]
        for id in exerciseIDs {
            if let stats = history.statistics(of: id) { statistics[id.rawValue] = StatisticsJSON(stats) }
            let trend = history.oneRepMaxTrend(of: id)
            if !trend.isEmpty {
                trends[id.rawValue] = trend.map { TrendPointJSON(date: $0.date.description, session: $0.sessionID.uuidString,
                                                                 oneRepMax: $0.oneRepMax.kilograms) }
            }
        }

        let ranges: [(ExerciseID, String, String)] = [
            ("barbell-bench-press", "2026-09-01", "2026-09-30"), ("barbell-bench-press", "2026-10-01", "2026-12-31"),
            ("pull-up", "2026-09-01", "2026-10-15"), ("assisted-pull-up", "2026-08-01", "2026-12-31"),
            ("one-arm-dumbbell-row", "2026-09-15", "2026-11-15"), ("back-squat", "2026-11-01", "2026-11-01"),
            ("custom-golden-zercher-squat", "2026-08-01", "2026-12-31"), ("plank", "2026-09-01", "2026-12-31"),
            ("farmers-carry", "2026-09-01", "2026-12-31"), ("back-squat", "2027-01-01", "2027-01-31"),
        ]
        let inRange = ranges.map { id, from, through in
            RangeStatisticsJSON(exercise: id.rawValue, from: from, through: through,
                                statistics: history.statistics(of: id, from: LocalDate(from)!, through: LocalDate(through)!).map(StatisticsJSON.init))
        }

        var records: [String: [RecordJSON]] = [:]
        for session in finished {
            let found = history.records(in: session)
            if found.isEmpty { continue }
            records[session.id.uuidString] = found.map {
                RecordJSON(kind: $0.kind.rawValue, exercise: $0.exerciseID.rawValue, session: $0.sessionID.uuidString,
                           set: $0.setID.uuidString, value: $0.value, previous: $0.previous, load: $0.load?.kilograms)
            }
        }

        var weekly: [String: [String: [String: VolumeJSON]]] = [:]
        for (name, weekday) in [("monday", Weekday.monday), ("sunday", .sunday)] {
            var weeks: [String: [String: VolumeJSON]] = [:]
            for (week, muscles) in history.weeklyMuscleVolume(firstWeekday: weekday) {
                weeks[week.description] = volumeJSON(muscles)
            }
            weekly[name] = weeks
        }

        let benchSeptember = history.statistics(of: "barbell-bench-press", from: LocalDate("2026-09-01")!,
                                                through: LocalDate("2026-09-30")!)?.estimatedOneRepMax?.kilograms ?? 0
        let references: [MetricReference] = [
            .bestOneRepMax(exercise: "barbell-bench-press", from: LocalDate("2026-09-01")!, through: LocalDate("2026-09-30")!,
                           claimedKilograms: benchSeptember),
            .bestOneRepMax(exercise: "barbell-bench-press", from: LocalDate("2026-09-01")!, through: LocalDate("2026-09-30")!,
                           claimedKilograms: benchSeptember * 1.004),
            .bestOneRepMax(exercise: "barbell-bench-press", from: LocalDate("2026-09-01")!, through: LocalDate("2026-09-30")!,
                           claimedKilograms: benchSeptember + 10),
            .totalVolume(exercise: "back-squat", from: LocalDate("2026-08-01")!, through: LocalDate("2026-12-31")!,
                         claimedKilogramReps: 1000),
            .weeklySets(muscle: .chest, weekStarting: LocalDate("2026-09-28")!, firstWeekday: .monday, claimed: 6),
            .weeklySets(muscle: .neck, weekStarting: LocalDate("2026-09-28")!, firstWeekday: .monday, claimed: 0),
            MetricReference(name: "exercise.e1rm.best",
                            parameters: ["exercise": "barbell-bench-press", "from": "2026-13-01", "through": "2026-12-31"],
                            claimed: 100),
            MetricReference(name: "sleep.hours.mean", parameters: [:], claimed: 7.5),
        ]
        let metrics = references.map { reference -> MetricJSON in
            switch reference.verify(against: history) {
            case .verified(let actual): MetricJSON(reference: reference, status: "verified", actual: actual)
            case .mismatch(let actual): MetricJSON(reference: reference, status: "mismatch", actual: actual)
            case .unverifiable: MetricJSON(reference: reference, status: "unverifiable", actual: nil)
            }
        }

        let queries: [(String, Muscle?)] = [
            ("bench", nil), ("Bench Press", nil), ("db row", nil), ("pushup", nil), ("push-up", nil), ("PULL UP", nil),
            ("curl", .biceps), ("", .calves), ("squat", nil), ("rdl", nil), ("zercher", nil), ("café", nil),
            ("leg", .hamstrings), ("press", .frontDelts), ("kb swing", nil), ("ohp", nil), ("lat", nil),
        ]
        let search = queries.map { query, muscle in
            SearchJSON(query: query, muscle: muscle?.rawValue, results: library.search(query, muscle: muscle).map(\.id.rawValue))
        }

        return GoldenHistory(
            customExercises: [try JSONValue(encoding: custom)],
            sessions: try sessions.map { try JSONValue(encoding: $0) },
            expected: Expected(sets: sets, summaries: summaries, statistics: statistics, statisticsInRange: inRange,
                               trends: trends, records: records, weeklyVolume: weekly, metrics: metrics, search: search))
    }

    static func volumeJSON(_ muscles: [Muscle: MuscleVolume]) -> [String: VolumeJSON] {
        Dictionary(uniqueKeysWithValues: muscles.map { ($0.key.rawValue, VolumeJSON($0.value)) })
    }

    /// About three sessions a week from August to early November 2026, across
    /// daylight-saving changes in London, New York and Auckland, plus edge cases.
    static func makeSessions() -> [WorkoutSession] {
        var random = Seeded(state: 20_261_006)
        var counter = 0
        func nextID() -> UUID {
            counter += 1
            return uuid(counter)
        }
        let zones = ["America/New_York", "Europe/London", "Asia/Tokyo", "Pacific/Auckland", "UTC"]
        let plans: [[ExerciseID]] = [
            ["barbell-bench-press", "pull-up", "one-arm-dumbbell-row", "plank"],
            ["back-squat", "custom-golden-zercher-squat", "assisted-pull-up", "farmers-carry"],
            ["barbell-bench-press", "dip", "crunch", "running"],
            ["back-squat", "bulgarian-split-squat", "pull-up", "custom-deleted-exercise"],
        ]
        var sessions: [WorkoutSession] = []
        // 2026-08-03 12:00 UTC, a Monday.
        let firstDay = 1_785_758_400.0
        for index in 0..<42 {
            let zone = TimeZone(identifier: zones[index % zones.count])!
            // Starts drift through the day, so some land just before or after local midnight.
            let minutes = Double(random.int(0...(24 * 60 - 1)))
            let start = Date.milliseconds(Int64((firstDay + Double(index) * 2.3 * 86_400 + minutes * 60) * 1000))
            let plan = plans[index % plans.count]
            var exercises: [PerformedExercise] = []
            var clock = start
            for exerciseID in plan {
                var sets: [PerformedSet] = []
                let count = random.int(2...5)
                for setIndex in 0..<count {
                    clock = clock.addingTimeInterval(Double(random.int(60...240)))
                    sets.append(makeSet(exerciseID, index: setIndex, progress: index, at: clock, id: nextID(), random: &random))
                }
                exercises.append(PerformedExercise(id: nextID(), exerciseID: exerciseID, sets: sets))
            }
            let bodyweight: Mass? = random.chance(15) ? nil : (random.chance(50) ? .kg(80 + Double(random.int(-20...20)) / 10)
                                                                               : .lb(176 + Double(random.int(-40...40)) / 10))
            let finished = index != 41
            sessions.append(WorkoutSession(id: nextID(), name: "Session \(index + 1)", startedAt: start,
                                           endedAt: finished ? clock.addingTimeInterval(120) : nil, timeZone: zone,
                                           bodyweight: bodyweight, exercises: exercises))
        }
        // Two sessions with the same start, ordered by ID.
        let tie = Date.milliseconds(1_790_000_000_000)
        for _ in 0..<2 {
            let setID = nextID()
            let performedID = nextID()
            sessions.append(WorkoutSession(id: nextID(), name: "Tie", startedAt: tie, endedAt: tie.addingTimeInterval(1800),
                                           timeZone: TimeZone(identifier: "America/New_York")!, bodyweight: .kg(81),
                                           exercises: [PerformedExercise(id: performedID, exerciseID: "barbell-bench-press", sets: [
                                               PerformedSet(id: setID, efforts: [Effort(reps: 3, load: .kg(110))], rir: 1, completedAt: tie),
                                           ])]))
        }
        return sessions
    }

    static func makeSet(_ exerciseID: ExerciseID, index: Int, progress: Int, at date: Date, id: UUID,
                        random: inout Seeded) -> PerformedSet {
        let growth = Double(progress) * 0.6
        let completed: Date? = random.chance(8) ? nil : date
        let rir: Double? = random.chance(20) ? nil : Double(random.int(0...12)) / 2
        func load(_ kilograms: Double) -> Mass {
            random.chance(30) ? .lb((kilograms / 0.453_592_37 / 2.5).rounded() * 2.5) : .kg((kilograms / 1.25).rounded() * 1.25)
        }
        switch exerciseID {
        case "plank":
            return PerformedSet(id: id, efforts: [Effort(duration: Double(random.int(30...120)))], completedAt: completed)
        case "running":
            return PerformedSet(id: id, efforts: [Effort(duration: Double(random.int(600...1800)),
                                                         distance: Double(random.int(1500...5000)))], completedAt: completed)
        case "farmers-carry":
            return PerformedSet(id: id, efforts: [Effort(load: load(40 + growth), distance: Double(random.int(20...60)))],
                                completedAt: completed)
        case "one-arm-dumbbell-row", "bulgarian-split-squat":
            let side: Side? = random.chance(80) ? (index % 2 == 0 ? .left : .right) : nil
            return PerformedSet(id: id, side: side, efforts: [Effort(reps: random.int(6...14), load: load(25 + growth / 2))],
                                rir: rir, completedAt: completed)
        case "pull-up", "dip", "crunch":
            let added: Mass? = random.chance(40) ? load(Double(random.int(0...20))) : nil
            return PerformedSet(id: id, kind: random.chance(15) ? .failure : .standard,
                                efforts: [Effort(reps: random.int(3...25), load: added)], rir: rir, completedAt: completed)
        case "assisted-pull-up":
            return PerformedSet(id: id, efforts: [Effort(reps: random.int(5...12), load: load(Double(random.int(10...40))))],
                                rir: rir, completedAt: completed)
        default:
            let base = (exerciseID == "back-squat" ? 120.0 : exerciseID == "barbell-bench-press" ? 85 : 70) + growth
            if index == 0 {
                return PerformedSet(id: id, kind: .warmUp, efforts: [Effort(reps: 8, load: load(base * 0.5))], completedAt: completed)
            }
            let roll = random.int(0...9)
            if roll == 0 {
                return PerformedSet(id: id, kind: .drop, efforts: [Effort(reps: random.int(5...8), load: load(base)),
                                                                   Effort(reps: random.int(4...8), load: load(base * 0.8)),
                                                                   Effort(reps: random.int(3...8), load: load(base * 0.6))],
                                    rir: random.chance(50) ? nil : 1, completedAt: completed)
            }
            if roll == 1 {
                return PerformedSet(id: id, kind: .myo, efforts: [Effort(reps: random.int(10...15), load: load(base * 0.6)),
                                                                  Effort(reps: 4, load: load(base * 0.6))],
                                    rir: nil, completedAt: completed)
            }
            let reps = roll == 2 ? random.int(21...30) : random.int(1...12)
            let entry: Mass? = roll == 3 ? nil : load(base + Double(random.int(-10...10)))
            return PerformedSet(id: id, efforts: [Effort(reps: reps, load: entry)], rir: rir, completedAt: completed)
        }
    }
}
